# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='articles_image', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='articles_video', verbose_name='Видео'),
        ),
    ]
