# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170323_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('content', models.TextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Анонс',
                'verbose_name_plural': 'Анонсы',
                'ordering': ('-pk',),
            },
        ),
    ]
